import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content=" hunting blogs nextJS "></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <nav className={styles.mainnav}>
          <ul>
            <Link href="./">  <li>Home</li></Link>
            <Link href="./about">  <li>About</li></Link>
            <Link href="./contact">  <li>Contact</li></Link>
            <Link href="./blog">  <li>Blog</li></Link>
          </ul>
        </nav>
        <main className={styles.main}>
          <h1>Hunting Coders</h1>
          <p>A Blog by the coder for the Coders</p>

          <div className="blogs">
            <h2>Popular Blogs</h2>
            <div className="blogItem">
              <h2>We are learning Next JS </h2>
              <p>To learn Next JS one must need to learn js and react </p>
            </div>
            <div className="blogItem">
              <h2>We are learning Next JS </h2>
              <p>To learn Next JS one must need to learn js and react </p>
            </div>{" "}
            <div className="blogItem">
              <h2>We are learning Next JS </h2>
              <p>To learn Next JS one must need to learn js and react </p>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
